### Shop Regist
POST http://{{host}}/{{version}}/{{division}}
Content-Type: application/json

{
  "mall_id": "bpmt001"
}

### Shop Find One
GET http://{{host}}/{{version}}/{{division}}/1
Accept: application/json

###